import type { ActionRow, SessionRow, UserRow } from './state.js';

function e(value:unknown):string { return String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!)); }

function page(title:string,body:string,opts:{csrf?:string;user?:UserRow}={}):string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta name="csrf-token" content="${e(opts.csrf??'')}"><title>${e(title)} · Artifact Apps</title><style>
:root{color-scheme:dark;--bg:#07101d;--panel:#0f1c2e;--line:#293c56;--text:#edf5ff;--muted:#9fb1c9;--accent:#55d9ff;--good:#73e6b1;--bad:#ff8b9b}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% -20%,#193b61,transparent 38rem),var(--bg);color:var(--text);font:16px/1.55 system-ui,sans-serif}a{color:var(--accent)}header{border-bottom:1px solid var(--line);background:#07101ddd;position:sticky;top:0;backdrop-filter:blur(12px);z-index:2}header>div,main{width:min(1100px,calc(100% - 28px));margin:auto}header>div{display:flex;justify-content:space-between;align-items:center;padding:13px 0}.brand{font-weight:850}.user{color:var(--muted);font-size:.9rem}main{padding:34px 0 80px}.auth{max-width:520px;margin:5vh auto}.card{background:linear-gradient(145deg,#11233a,var(--panel));border:1px solid var(--line);border-radius:18px;padding:22px;box-shadow:0 24px 70px #0007;margin:16px 0}h1{font-size:clamp(2rem,5vw,3.4rem);line-height:1.05;letter-spacing:-.045em;margin:0 0 12px}h2{margin:4px 0 14px}.muted{color:var(--muted)}label{display:block;margin:13px 0 6px;font-weight:700}input,select,textarea,button{font:inherit}input,select,textarea{width:100%;padding:11px 12px;border-radius:10px;border:1px solid var(--line);background:#07111f;color:var(--text)}textarea{min-height:100px}button,.button{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:10px;padding:11px 15px;background:var(--accent);color:#04101a;font-weight:850;text-decoration:none;cursor:pointer;margin-top:12px}button.secondary,.button.secondary{background:#20344e;color:var(--text)}button.danger{background:var(--bad)}.row{display:flex;gap:10px;flex-wrap:wrap}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.grid>*{min-width:0}.wide{grid-column:1/-1}.table{max-width:100%;overflow:auto;border:1px solid var(--line);border-radius:12px}table{width:100%;border-collapse:collapse;min-width:600px}th,td{text-align:left;padding:10px 12px;border-bottom:1px solid var(--line)}th{color:var(--muted);font-size:.8rem;text-transform:uppercase}.status{min-height:24px;margin-top:12px}.status.error{color:var(--bad)}.status.ok{color:var(--good)}code{background:#06101d;padding:.15em .35em;border-radius:6px}.pill{display:inline-block;padding:3px 8px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:.8rem}@media(max-width:700px){.grid{grid-template-columns:1fr}.card{padding:17px}header .user{display:none}}
</style></head><body><header><div><a class="brand" href="/">Artifact Apps</a><span class="user">${opts.user?`${e(opts.user.username)} · ${e(opts.user.role)}`:'Passkey-first access'}</span></div></header><main>${body}</main><script src="/assets/app.js" defer></script></body></html>`;
}

export function renderLogin():string { return page('Sign in',`<section class="auth"><span class="pill">Private personal app</span><h1>Sign in with a passkey</h1><p class="muted">Your artifact viewer links remain read-only. Actions and personal data require your account.</p><div class="card"><button id="passkey-login">Continue with passkey</button><p id="status" class="status" role="status"></p><hr style="border:0;border-top:1px solid var(--line);margin:20px 0"><a href="/recovery">Recover account with password</a></div></section>`); }
export function renderRecovery():string { return page('Recover account',`<section class="auth"><h1>Recover your account</h1><p class="muted">Recovery creates a restricted session. You must register a new passkey before accessing apps or admin tools.</p><form id="recovery-form" class="card"><label for="username">Username</label><input id="username" name="username" autocomplete="username" required><label for="password">Recovery password</label><input id="password" name="password" type="password" autocomplete="current-password" minlength="14" required><button>Start recovery</button><p id="status" class="status" role="status"></p></form><div id="passkey-enroll" class="card" hidden><h2>Register a new passkey</h2><label for="passkey-label">Device label</label><input id="passkey-label" value="Primary device" maxlength="80"><button id="register-passkey">Register passkey</button></div></section>`); }
export function renderInvite(token:string):string { return page('Accept invitation',`<section class="auth"><h1>Accept invitation</h1><p class="muted">Set a recovery password, then register a passkey. The password is used only if you lose every passkey.</p><form id="invite-form" class="card" data-token="${e(token)}"><label for="password">Recovery password</label><input id="password" name="password" type="password" minlength="14" required><button>Continue to passkey</button><p id="status" class="status" role="status"></p></form><div id="passkey-enroll" class="card" hidden><label for="passkey-label">Device label</label><input id="passkey-label" value="Primary device"><button id="register-passkey">Register passkey</button></div></section>`); }

export function renderAdmin(input:{user:UserRow;csrf:string;users:UserRow[];passkeys:Record<string,unknown>[];sessions:SessionRow[];actions:ActionRow[];outbox:Record<string,unknown>[];artifacts:Array<{slug:string;title?:string;createdAt:string;expiresAt?:string;revokedAt?:string}>;audit:Record<string,unknown>[]}):string {
  const userRows=input.users.map((u)=>`<tr><td>${e(u.username)}</td><td>${e(u.role)}</td><td>${e(u.status)}</td><td>${e(u.scopes.join(', '))}</td><td><button class="secondary user-status" data-user="${e(u.id)}" data-status="${u.status==='suspended'?'active':'suspended'}">${u.status==='suspended'?'Activate':'Suspend'}</button> <button class="secondary revoke-user-sessions" data-user="${e(u.id)}">Revoke sessions</button></td></tr>`).join('');
  const artifactRows=input.artifacts.map((a)=>`<tr><td>${e(a.title??a.slug)}</td><td><code>${e(a.slug)}</code></td><td>${e(a.createdAt)}</td><td>${e(a.revokedAt?'revoked':a.expiresAt??'active')}</td><td>${a.revokedAt?'—':`<button class="danger revoke-artifact" data-slug="${e(a.slug)}">Revoke link</button>`}</td></tr>`).join('');
  const actionRows=input.actions.map((a)=>`<tr><td>${e(a.action)}</td><td>${e(a.state)}</td><td>${e(a.appId)}</td><td>${e(a.createdAt)}</td></tr>`).join('');
  const sessionRows=input.sessions.map((s)=>`<tr><td>${e(s.userId)}</td><td>${e(s.kind)}</td><td>${e(s.lastUsedAt)}</td><td>${e(s.revokedAt?'revoked':'active')}</td></tr>`).join('');
  const passkeyRows=input.passkeys.map((p)=>`<tr><td>${e(p.user_id)}</td><td>${e(p.label)}</td><td>${e(p.created_at)}</td><td><button class="danger delete-passkey" data-passkey="${e(p.id)}">Remove</button></td></tr>`).join('');
  const outboxRows=input.outbox.map((o)=>`<tr><td>${e(o.kind)}</td><td>${e(o.state)}</td><td>${e(o.attempts)}</td><td>${e(o.last_error??'—')}</td><td>${e(o.created_at)}</td></tr>`).join('');
  return page('Admin',`<h1>Artifact administration</h1><p class="muted">Manage identity, artifacts, action policy, and audit history. Secrets and credential material are never shown.</p><div class="grid"><section class="card"><h2>Create invitation</h2><form id="invite-create"><label>Username</label><input name="username" required><label>Role</label><select name="role"><option>member</option><option>viewer</option><option>admin</option></select><label>Scopes</label><input name="scopes" value="jobs:feedback,reports:ask"><button>Create invitation</button><p id="invite-result" class="status"></p></form></section><section class="card"><h2>Controls</h2><p><a href="/admin/files/">Legacy file browser</a></p><button id="logout" class="secondary">Sign out</button><p class="muted">Emergency mutation control and per-app limits are configured server-side in this MVP.</p></section><section class="card wide"><h2>Users</h2><div class="table"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Scopes</th><th>Actions</th></tr></thead><tbody>${userRows}</tbody></table></div></section><section class="card wide"><h2>Passkeys</h2><div class="table"><table><thead><tr><th>User ID</th><th>Label</th><th>Created</th><th>Action</th></tr></thead><tbody>${passkeyRows}</tbody></table></div></section><section class="card wide"><h2>Artifacts</h2><div class="table"><table><thead><tr><th>Title</th><th>Slug</th><th>Created</th><th>Status</th><th>Action</th></tr></thead><tbody>${artifactRows}</tbody></table></div></section><section class="card wide"><h2>Actions</h2><div class="table"><table><thead><tr><th>Action</th><th>State</th><th>App</th><th>Created</th></tr></thead><tbody>${actionRows}</tbody></table></div></section><section class="card wide"><h2>Outbox</h2><div class="table"><table><thead><tr><th>Kind</th><th>State</th><th>Attempts</th><th>Last error</th><th>Created</th></tr></thead><tbody>${outboxRows}</tbody></table></div></section><section class="card wide"><h2>Sessions</h2><div class="table"><table><thead><tr><th>User ID</th><th>Kind</th><th>Last used</th><th>Status</th></tr></thead><tbody>${sessionRows}</tbody></table></div></section><section class="card wide"><h2>Audit</h2><p class="muted">${input.audit.length} recent authentication, authorization, and action events.</p></section></div>`,{csrf:input.csrf,user:input.user});
}

export function renderJobs(user:UserRow,csrf:string):string { return page('Jobs',`<h1>Job feedback</h1><p class="muted">This authenticated app writes structured feedback deterministically, then queues a bounded Hermes event.</p><div class="grid"><form id="job-feedback" class="card"><h2>Record feedback</h2><label>Job ID</label><input name="jobId" required maxlength="100"><label>Disposition</label><select name="disposition"><option>interested</option><option>maybe</option><option>not_interested</option><option>needs_review</option></select><label>Note</label><textarea name="note" maxlength="2000"></textarea><button>Save feedback</button><p id="status" class="status"></p></form><form id="report-question" class="card"><h2>Ask Hermes</h2><label>Report ID</label><input name="reportId" required><label>Question</label><textarea name="question" required maxlength="1000"></textarea><button>Queue question</button><p id="question-status" class="status"></p></form></div>`,{csrf,user}); }

export const browserScript = `
const $=(s)=>document.querySelector(s); const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.content||'';
const b64=(buf)=>{const bytes=new Uint8Array(buf);let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'')};
const from64=(s)=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((s.length+3)%4)),c=>c.charCodeAt(0));
const credentialJSON=(c)=>({id:c.id,rawId:b64(c.rawId),type:c.type,clientExtensionResults:c.getClientExtensionResults(),authenticatorAttachment:c.authenticatorAttachment,response:c.response.attestationObject?{attestationObject:b64(c.response.attestationObject),clientDataJSON:b64(c.response.clientDataJSON),transports:c.response.getTransports?.()||[]}:{authenticatorData:b64(c.response.authenticatorData),clientDataJSON:b64(c.response.clientDataJSON),signature:b64(c.response.signature),userHandle:c.response.userHandle?b64(c.response.userHandle):null}});
async function json(url,options={}){const r=await fetch(url,{...options,headers:{'content-type':'application/json','x-csrf-token':csrf(),...(options.headers||{})}});const data=await r.json().catch(()=>({error:'Request failed'}));if(!r.ok)throw new Error(data.error||'Request failed');return data}
async function registerPasskey(){const label=$('#passkey-label')?.value||'Passkey';const o=await json('/auth/passkeys/register/options',{method:'POST',body:JSON.stringify({label})});o.challenge=from64(o.challenge);o.user.id=from64(o.user.id);(o.excludeCredentials||[]).forEach(x=>x.id=from64(x.id));const c=await navigator.credentials.create({publicKey:o});await json('/auth/passkeys/register/verify',{method:'POST',body:JSON.stringify({flowId:o.flowId,response:credentialJSON(c)})});location.href='/app/jobs'}
$('#passkey-login')?.addEventListener('click',async()=>{try{const o=await json('/auth/passkeys/authenticate/options',{method:'POST',body:'{}'});o.challenge=from64(o.challenge);(o.allowCredentials||[]).forEach(x=>x.id=from64(x.id));const c=await navigator.credentials.get({publicKey:o});await json('/auth/passkeys/authenticate/verify',{method:'POST',body:JSON.stringify({flowId:o.flowId,response:credentialJSON(c)})});location.href='/app/jobs'}catch(e){$('#status').textContent=e.message;$('#status').className='status error'}});
$('#recovery-form')?.addEventListener('submit',async(e)=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));const result=await json('/auth/recovery',{method:'POST',body:JSON.stringify(d)});document.querySelector('meta[name="csrf-token"]').content=result.session.csrfToken;$('#passkey-enroll').hidden=false;$('#status').textContent='Recovery verified. Register a new passkey.'}catch(err){$('#status').textContent=err.message;$('#status').className='status error'}});
$('#invite-form')?.addEventListener('submit',async(e)=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));const token=e.target.dataset.token;const result=await json('/auth/invitations/'+encodeURIComponent(token)+'/begin',{method:'POST',body:JSON.stringify(d)});document.querySelector('meta[name="csrf-token"]').content=result.session.csrfToken;$('#passkey-enroll').hidden=false;e.target.hidden=true}catch(err){$('#status').textContent=err.message;$('#status').className='status error'}});
$('#register-passkey')?.addEventListener('click',()=>registerPasskey().catch(e=>{const s=$('#status');if(s){s.textContent=e.message;s.className='status error'}}));
$('#invite-create')?.addEventListener('submit',async(e)=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));d.scopes=String(d.scopes||'').split(',').map(x=>x.trim()).filter(Boolean);const r=await json('/admin/api/invitations',{method:'POST',body:JSON.stringify(d)});$('#invite-result').innerHTML='<a href="'+r.invitationUrl+'">Copy invitation link</a>'}catch(err){$('#invite-result').textContent=err.message}});
async function waitForAction(appId,actionId,status){for(let i=0;i<150;i++){await new Promise(r=>setTimeout(r,2000));const r=await json('/app/'+encodeURIComponent(appId)+'/actions/'+encodeURIComponent(actionId));if(r.action.state==='succeeded'){status.textContent=r.action.result?.summary||r.action.result?.message||'Completed';status.className='status ok';return}if(r.action.state==='failed'){status.textContent=r.action.error||'Action failed';status.className='status error';return}status.textContent=r.action.state==='running'?'Hermes is working…':'Queued…'}status.textContent='Still running. You can safely return later.'}
async function submitAction(form,action,statusId,makePayload){form?.addEventListener('submit',async(e)=>{e.preventDefault();const id=crypto.randomUUID();const s=$(statusId);s.textContent='Queued…';try{const data=Object.fromEntries(new FormData(e.target));const r=await json('/app/jobs/actions/'+action,{method:'POST',headers:{'idempotency-key':id},body:JSON.stringify({clientActionId:id,schemaVersion:1,payload:makePayload(data)})});if(r.action.state==='succeeded'){s.textContent=r.action.result?.message||'Saved';s.className='status ok'}else{void waitForAction('jobs',r.action.id,s)}}catch(err){s.textContent=err.message;s.className='status error'}})}
submitAction($('#job-feedback'),'job.feedback.submit','#status',d=>({jobId:d.jobId,disposition:d.disposition,note:d.note||undefined}));submitAction($('#report-question'),'report.question.ask','#question-status',d=>({reportId:d.reportId,question:d.question}));
$('#logout')?.addEventListener('click',async()=>{await json('/auth/logout',{method:'POST',body:'{}'});location.href='/login'});
document.querySelectorAll('.revoke-artifact').forEach((button)=>button.addEventListener('click',async()=>{if(!confirm('Revoke this viewer link?'))return;await json('/admin/api/artifacts/'+encodeURIComponent(button.dataset.slug)+'/revoke',{method:'POST',body:'{}'});location.reload()}));
document.querySelectorAll('.user-status').forEach((button)=>button.addEventListener('click',async()=>{await json('/admin/api/users/'+encodeURIComponent(button.dataset.user)+'/status',{method:'POST',body:JSON.stringify({status:button.dataset.status})});location.reload()}));
document.querySelectorAll('.revoke-user-sessions').forEach((button)=>button.addEventListener('click',async()=>{if(!confirm('Revoke all sessions for this user?'))return;await json('/admin/api/users/'+encodeURIComponent(button.dataset.user)+'/revoke-sessions',{method:'POST',body:'{}'});location.reload()}));
document.querySelectorAll('.delete-passkey').forEach((button)=>button.addEventListener('click',async()=>{if(!confirm('Remove this passkey?'))return;await json('/admin/api/passkeys/'+encodeURIComponent(button.dataset.passkey),{method:'DELETE'});location.reload()}));
`;
